[package]
name = "fern"
version = "0.0.1"
authors = ["Felipe Sere <felipesere@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ignore = "0.4.12"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.11"
git-version = "0.3.4"
pico-args = "0.3.1"
thiserror = "1.0.11"

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
